# Generated by Django 5.2.8 on 2025-11-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='join_date',
            new_name='joined_date',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('volunteer', 'Volunteer'), ('educator', 'Educator'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
